### ISSUE TITLE
cant read .env on multisite

### ISSUE THREAD

**Issue by buruhsd** [gecche/laravel-multidomain#1]
hi, i try to make a laravel apps with multi site and multi domain with different database in single code base. i try to config .env each site. but when i try to config:cache it still using one database. im using laravel 5.8

**Comment by gecche** [comment]
Hi,

tank you for your feedback.

Honestly, I did never try the command config:cache so it can be that there
is a problem with such command.
I will test config:cache as soon as possible.

A question: your app works in multi domain without using config:cache?

Cheers

Giacomo Terreni



Il giorno ven 8 mar 2019 alle ore 05:44 muhammad al jawad <
notifications@github.com> ha scritto:

**Comment by buruhsd** [comment]
no it doesnt work, because my apps cant work if app_key in .env null.

**Comment by buruhsd** [comment]
even i try to not using config:cache, it still using the first db

**Comment by gecche** [comment]
Ok, without the config:cache is strange.
Could you send me more detailed info about your configuration and how do
you use the app?
I will try to check in the weekend.

Thank you

giacomo

Il giorno ven 8 mar 2019 alle ore 11:34 muhammad al jawad <
notifications@github.com> ha scritto:

**Comment by buruhsd** [comment]
can i just give you an my github repo?

**Comment by buruhsd** [comment]
this is my code and configuration

**Comment by gecche** [comment]
ok thanks, i’ll try to check all in the we

giacomo

Inviato da iPhone

**Comment by buruhsd** [comment]
Thank you sir,

**Comment by buruhsd** [comment]
https://github.com/buruhsd/subdomain

**Comment by gecche** [comment]
Hi,

I've just checked your code.

1 - For now, the package definitely does not work with config:cache.
You have to remove the file /bootstrap/cache/config.php either manually or
by using the config:clear command. I will try to update the package as soon
as possible if it can be done.

2 - Without the config cached, it seems to work properly even if I did not
tested before with Laravel 5.8. I set up your environment on my machine and
I did not change any file. Just tried to do those two artisan commands

- php artisan migrate --domain=test.subdomain.test
- php artisan migrate --domain=site2.subdomain.test

They both worked properly creating the tables in the two databases listed
in the two .env files.
Furthermore, in /routes/web.php I tried to put the "echo" line:

Route::get('/', function () {
    echo '<h1>'.env('DB_DATABASE').'</h1>';
    return view('welcome');
});

and again correctly it displayed to me the correct database name when using

http://test.subdomain.test

and

http://site2.subdomain.test

in the browser.

Let me now If I don't understood something.

Cheers

Giacomo







Il giorno sab 9 mar 2019 alle ore 07:28 muhammad al jawad <
notifications@github.com> ha scritto:

**Comment by buruhsd** [comment]
i tried this, test.subdomain.test using customer2 db just like i write on .env.test.subdomain.test. but when i try site2.subdomain.test it still using another db just like i write on .env not .env.site2.subdomain.test like i want

**Comment by buruhsd** [comment]
site2.subdomain.test only read .env.site2.subdomain.test on console, but if im using web browser. it show different database config. i dont know why

**Comment by buruhsd** [comment]
oh sorry, im done. it worked perfectly. thank you very much

**Comment by gecche** [comment]
Hi, I just released a new version which works also by using the
config:cache command.

See you

Giacomo

P.S. If you liked the package please leave me a star :)

Il giorno sab 9 mar 2019 alle ore 20:35 muhammad al jawad <
notifications@github.com> ha scritto:
