### ISSUE TITLE
Horizon without documentation

### ISSUE THREAD

**Issue by raulamoretti** [gecche/laravel-multidomain#103]
I tried push a append in documentation with:

`#### Horizon install

We need change Provider of Horizon to handle multi domains!
Thanks to 

Installation steps:
1.  Install Laravel Horizon

2. Replace the Laravel Horizon import at the very top of the `app/Providers/HorizonServiceProvider.php` file.

```php
//use Laravel\Horizon\HorizonApplicationServiceProvider;
use Gecche\Multidomain\Horizon\HorizonApplicationServiceProvider;
```

3. Ready!`

**Comment by gecche** [comment]
Thank you very much :)
Sorry for the delay...
Do you want to create a pull request? So, you will be listed as a contributor.

Cheers

Giacomo

**Comment by raulamoretti** [comment]
Hey Giacomo!

Yes, please do.

Thanks, Raul

**Comment by gecche** [comment]
Hi,

finally you didn't create a PR request... however I just updated the docs with your notes. (and not only).

Thanks

Giacomo
