### ISSUE TITLE
.env.domain.com doesnt get loaded or read

### ISSUE THREAD

**Issue by abbasmashaddy72** [gecche/laravel-multidomain#104]
#92 

Same issue Hear @edwinsmasher Please reopen it again

**Comment by abbasmashaddy72** [comment]
> Could you check if the SERVER_NAME server variable is instantiated in your execution environment? If not you can try to switch for example to HTTP_HOST, following the instructions in the docs in the section: "Customizing the detection of HTTP domains"

I have followed all the instructions but not working as excepted

below both code are not working

str_replace('{app_name}', env('APP_NAME'),
{{ config('app.name', 'Laravel') }}

**Comment by abbasmashaddy72** [comment]
You can Check my repo: [Repo Link](https://github.com/abbasmashaddy72/medcare)

**Comment by gecche** [comment]
Hi,

I have seen your repo, but, as pointed out in the "Customizing the detection of HTTP domains" section in the docs, could you try to put this snippet in the bootstrap/app.php file? 

```
$domainParams = [
    'domain_detection_function_web' => function() {
        return \Illuminate\Support\Arr::get($_SERVER,'HTTP_HOST');
    }
];

//$app = new Illuminate\Foundation\Application(
$app = new Gecche\Multidomain\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__), null, $domainParams
);
```

**Comment by abbasmashaddy72** [comment]
> Hi,
> 
> I have seen your repo, but, as pointed out in the "Customizing the detection of HTTP domains" section in the docs, could you try to put this snippet in the bootstrap/app.php file?
> 
> ```
> $domainParams = [
>     'domain_detection_function_web' => function() {
>         return \Illuminate\Support\Arr::get($_SERVER,'HTTP_HOST');
>     }
> ];
> 
> //$app = new Illuminate\Foundation\Application(
> $app = new Gecche\Multidomain\Foundation\Application(
>     $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__), null, $domainParams
> );
> ```

Thanks, Brother, It is Working Now

few Doubts
1. Will it work with https also
2. Migration If change DB for Domain how to Migrate it.
I tried `php artisan migrate --seed --domain=medecare.test` but was not able to migrate it migrates from .env not from .env.medecare.test

**Comment by gecche** [comment]
1 - Will it work with https also

Yes

2 - Migration If change DB for Domain how to Migrate it.
I tried php artisan migrate --seed --domain=medecare.test but was not able to migrate it migrates from .env not from .env.medecare.test

All the laravel commands work with the domain option. However you can't use the --seed option because it launches another command internally without the domain option

Cheers

**Comment by abbasmashaddy72** [comment]
Thanks Brother
