### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by webnatrix** [gecche/laravel-multidomain#105]
Paragraph 3 states that it is necessary to replace it with a new Laravel 10, it cannot be commented out
`//Illuminate\Queue\QueueServiceProvider::class,
Gecche\Multidomain\Queue\QueueServiceProvider::class,`

And php artisan vendor:publish what exactly to publish is not specified

**Comment by gecche** [comment]
Hi,

Regarding the first problem, I don't understand what do you mean.

For the publishing section you have to choose my package in the list you get at screen.

Cheers

Giacomo
