### ISSUE TITLE
Laravel/horizon is not working when trying to implement in windows environment.

### ISSUE THREAD

**Issue by Ashraf514** [gecche/laravel-multidomain#106]
when try to install "laravel/horizon"
  - laravel/horizon v2.1.0 requires ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
 
  
![image](https://github.com/gecche/laravel-multidomain/assets/56148841/22a869d7-d9a4-46e6-8130-0f291f80a761)

I checked my "php.ini" there's no such extension, this extension is only available for Linux based Operating systems.
I'm using xampp server on my system, how can I fix this issue?

**Comment by gecche** [comment]
Hi, as I am
using Linux I'm not able to help you... anyway I think that you should ask to the people of the Horizon package as the extension is required by that package and not this one!

Cheers

giacomo
