### ISSUE TITLE
Laravel 11 Compatibility

### ISSUE THREAD

**Issue by anony253** [gecche/laravel-multidomain#110]
Hi,

Would it be possible to update this package to be compatible with latest Laravel 11 please ?

Regards,
anony253

**Comment by gecche** [comment]
Hi,

I've just added a new branch v11 where I've done some preliminary work. 
The package seems to work but as Laravel 11 introduces a new Application structure, the migration is not straightforward and even more the packages I need to run my test suite are not fully updated yet for Laravel 11.
I plan to release a new tag as soon as possible, but I need to do more manual tests in the next days.

If you (or anyone else) want to try the package with Laravel 11 you can use directly the v11 branch in your composer settings.

Cheers

Giacomo

**Comment by gecche** [comment]
Just release v11.0
