### ISSUE TITLE
Feature/Unit Tests have no --domain option, so no .env loaded, so they can not working if needed

### ISSUE THREAD

**Issue by MrCanan** [gecche/laravel-multidomain#115]
Hi,

### New problem/question
- The Feature/Unit test can not work, due to do not have "--domain" option, so .env is missing to load correct database
> I got "Database file at path [__ABSOLUTE_PATH__/database/database.sqlite] does not exist. Ensure this is an absolute path to the database." error (__ABSOLUTE_PATH__ is a example)

### Environnement
- Laravel 11.5.0 (lastest)
- laravel-multidomain 11.0 (lastest)

### Env
- Delete `.env`
- Create `.env.test.lan`

```
DB_DATABASE=__ABSOLUTE_PATH__/database/database_test.sqlite
```

### Database
- Delete `database/database.sqlite`
- Create `database/database_test.sqlite`

### Feature/Unit Test
`tests\Feature\CustomTest.php`

```
<?php

namespace Tests\Feature;

use Tests\TestCase;

use Illuminate\Foundation\Testing\RefreshDatabase;

use App\Models\User;
use Database\Seeders\UserSeeder;

class CustomTest extends TestCase
{
    use RefreshDatabase;

    /**
     * test_get_db
     */
    public function test_get_db(): void
    {
        $oResponse = $this->get('/');

        $oResponse->assertStatus(302);
    }
}
```

### Run
`php artisan test --testsuite=Feature --stop-on-failure --filter CustomTest`

Thank you in advance for any help,
Best regards

**Comment by gecche** [comment]
Hi, I close the issue as is the same as #100. However I don't think that can be solved easily. :(

**Comment by MrCanan** [comment]
Hi back,

This is very annoying, because these tests are necessary

Do you have an idea?
Can I help you? (to test or other)

Best regards
