### ISSUE TITLE
Commands not recognised in v11

### ISSUE THREAD

**Issue by bafitu** [gecche/laravel-multidomain#116]
Hi,

I have issues with using custom commands in v11 from artisan e.g. artisan mycommand:dosomething
They are not recognised from the framework.

I did some digging and found that there was an issue with one of the functions that this package does not extend:

**src/Illuminate/Foundation/Console/Kernel.php** in **bootstrap** function there is a check **$this->shouldDiscoverCommands()**
and when I use "use Gecche\Multidomain\Foundation\Application" in the boostrap/app.php this function is always returning **false** resulting in no custom commands to be discovered.
because the check is: 
`get_class($this) === __CLASS__`
e.g. "Gecche\Multidomain\Foundation\Console\Kernel" === "Illuminate\Foundation\Console\Kernel"

if you had the same function in your Kernel class it will be ok because it will compare the same class.

Can you confirm thats the case and the package needs to be updated or I'm missing something?

**Comment by gecche** [comment]
Hi,

thanks for your feedback... I think you are right... that method should be replicated in the package Kernel class.
I was not aware of that feature.

If you are in hurry, could you do some simple tests and issue a pull request?

I can't code properly until (maybe) tomorrow or Friday

Let me know

Thanks

Giacomo

**Comment by gecche** [comment]
I just updated the package using your suggestions... thanks a lot!
