### ISSUE TITLE
Is it possible to have everything done automatically?

### ISSUE THREAD

**Issue by mrranger** [gecche/laravel-multidomain#119]
Is it possible for everything to be done automatically? I need the user to add his domain to my website, indicate the ip of my panel in the DNS records, and the theme he has chosen will be displayed on his website

**Comment by gecche** [comment]
Hi,

I'm not sure to have understood precisely your question, but If I have understood right, the answer is no.
At least, I think that you have to create an extrernal "admin" application that when an user add his domain, it fires some artisan commands in the mian application to accomplish your tasks.

Cheers

Giacomo
