### ISSUE TITLE
domain:add issue

### ISSUE THREAD

**Issue by hadariyair** [gecche/laravel-multidomain#121]
Hi,

Thanks for contributing the code to the community.

I have installed gecche/laravel-multidomain v 5.0 on laravel v 9.52.16, using composer and ran the php artisan vendor:publish which created the file config/domain.

Now I"m running the command sudo php artisan domain:add domain.name.com and getting the following error:

   BadMethodCallException 

  Method Illuminate\Foundation\Application::exactDomainStoragePath does not exist.

  at vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
    109▕      */
    110▕     public function __call($method, $parameters)
    111▕     {
    112▕         if (! static::hasMacro($method)) {
  ➜ 113▕             throw new BadMethodCallException(sprintf(
    114▕                 'Method %s::%s does not exist.', static::class, $method
    115▕             ));
    116▕         }
    117▕ 

  i   Bad Method Call: Did you mean Illuminate\Foundation\Application::useStoragePath() ? 

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

I will be thankful for your assistant

Yair

**Comment by gecche** [comment]
Hi,

it seems that the Application class which you are using, is the default Laravel Application class, but when installing my package you must replace that class with the package Application class in the bootstrap/app.php file as pointed out in the docs.

Let me know if this solves the issue

Cheers

Giacomo

**Comment by hadariyair** [comment]
Thanks for the answer.
When performing the change I"m getting the error

php artisan vendor:publish 
"
PHP Fatal error:  Uncaught Error: Class "Gecche\Multidomain\Foundation\Application" not found in /var/www/esbinaa-business/bootstrap/app.php:11
Stack trace:
#0 /var/www/esbinaa-business/artisan(20): require_once()
#1 {main}
  thrown in /var/www/esbinaa-business/bootstrap/app.php on line 11
"
My bootstrap/app.php looks like that:
`<?php

use Gecche\Multidomain\Foundation\Application;
/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
*/

//$app = new Illuminate\Foundation\Application(
$app = new Gecche\Multidomain\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

/*
|--------------------------------------------------------------------------
| Bind Important Interfaces
|--------------------------------------------------------------------------
*/

$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

/*
|--------------------------------------------------------------------------
| Return The Application
|--------------------------------------------------------------------------
*/

return $app;
`

My config/app.php looks like that:

` 'providers' => [

        ...
        Illuminate\Queue\QueueServiceProvider::class,
	...
    ],

    'providers' => Illuminate\Support\ServiceProvider::defaultProviders()->merge([
        // Package Service Providers...
    ])->replace([
        Illuminate\Queue\QueueServiceProvider::class => Gecche\Multidomain\Queue\QueueServiceProvider::class,
    ])->merge([
        // Added Service Providers (Do not remove this line)...
    ])->toArray(),`

Thanks in advance,
Yair

**Comment by hadariyair** [comment]
I managed - thanks Giacomo!!!
