### ISSUE TITLE
Heroku Config Vars

### ISSUE THREAD

**Issue by wasay** [gecche/laravel-multidomain#16]
Hi,
heroku.com only allows single config vars option from backend dashboard.

Is there any way to avoid using the .env.domain.com environment file?

In bootstrap/cache/config-domain.com; it would have been best if we can only set limitted variables and defaulting to values available from default values from .env file.

**Comment by gecche** [comment]
Hi,

I'm sorry but I don't understand what do you mean :)
Honestly I don't use and I don't know Heroku.

Maybe you could give a concrete example?

Cheers

Giacomo

**Comment by wasay** [comment]
That's alright.

I hope I can explain it as simple as possible.

Heroku free apps hosting does not have a ssh/ftp access, but logging in using the web heroku bash console on heroku.com, I am able to see the list of deployed files, but there is no .env file nor I was able to locate any file that may contain .env related config settings.

Heroku allows only through web control panel to add config (environment) variables under the app settings page. The config variables page is a simple CRUD operations page with two input fields per row, one for name and one for value. These config vars are dynamically converted as .env file variables; thus being available to laravel application.

As these config vars are for the entire laravel app; I don't see an option to customize the variables for specific domains using the files .env.domain.com.

I was wondering if I can use the config vars name to set domain specific environment variables within config/app.php at runtime?

DB_HOST_domain.com=abcd
DB_HOST_example.net=xyz

And also update the _config/app.php to dynamically set the domain specific variables. After evaluating domain name, if a DB_HOST + domain name environment variable is found, then set the app config variables to the values based on the domain name.

**Comment by gecche** [comment]
Hi,

ok, it's clearer than before, even I'm not sure to have understood all :)

However I think that my package is not suitable for your settings because if the CRUD Heroku page sets all the variables in the main .env  file and not in .env.domain.com files, you don't need my package at all because it always checks for the existence of the corresponding .env.domain.com file at the very start of a Laravel app. If the file does not exist, then it loads the standard .env file.

Probably all you are doing in app.php file could work, but I think it could work also without my package.

I hope this helps and I'm sorry if I missed something

Cheers

Giacomo

**Comment by wasay** [comment]
Thanks for the input.

Currently I am thinking of adding route groups to pass requests to different controllers; but it may still be not as clean as your implementation. 
But I will see how I may be able to accomplish it in app.php.

Thank you for creating laravel-multidomain; it's very informative and nicely setup folder structure.

You can close this ticket.

Thank you,
Wasay

**Comment by gecche** [comment]
Ok, thanks... an idea: can you create in Heroku the .env files from within the application? 
You could get the content of the main .env file as an array, change the values and then save the with the .env.domain name. 
It is a bit annoying but maybe it works.

Cheers

Giacomo

P.S. If you liked the package please leave a star If you haven't done yet ;)
