### ISSUE TITLE
Using public storage

### ISSUE THREAD

**Issue by Bailed** [gecche/laravel-multidomain#17]
Hi, I want to use the app/storage/{domain}/app/public folder to a favicon for each domain. What's the best way to access the this folder ...? In single domain I use symlink but not documented for your package.

**Comment by gecche** [comment]
Hi,

do you mean the symlink done via the 'storage:link' artisan command?
In that case, for now, as pointed out in #15 you have to do manually as many symlinks as many domains you have.

Let me know if this helps

Cheers

Giacomo

**Comment by Bailed** [comment]
Actually I have :
1) .env.domain.test with 

> APP_URL= https://domain.test
 and
> APP_PUBLIC_STORAGE=-domain_test

2) filesystems.php
> 'public' => [
>             'driver' => 'local',
>             'root' => storage_path('app/public'),
>             'url' => env('APP_URL').'/storage'.env('APP_PUBLIC_STORAGE'),
>             'visibility' => 'public',
>         ],

3) In my app/public 

> lrwxrwxrwx 1 user psacln   71 Jan  7 16:46 storage-domain_test -> /var/www/vhosts/app/httpdocs/storage/domain_test/

But {{ asset('storage/image.png') }} doesn't work ......

**Comment by gecche** [comment]
Hi,

maybe I'm wrong but you are using `asset('storage/image.png')` where "storage" does not exist. You could try this:

```
{{ asset('storage-domain_test/image.png') }}
```

or maybe better:

```
{{ asset('storage'.env('APP_PUBLIC_STORAGE').'/image.png') }}
```

Let me know if it works.

Cheers 

Giacomo

**Comment by Bailed** [comment]
Hi, 
It was that. But in fact it let the full path appear in the url (storage-domain_test/file.do) what I doesn't want. 

Instead, I saw that you overwrite store_path function with your package. So I wrote a new route for storage/{filename} and it works like a charm.

```
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/public/'.$filename);
    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});
```

Thanks !

**Comment by abbasmashaddy72** [comment]
> Hi,
> 
> maybe I'm wrong but you are using `asset('storage/image.png')` where "storage" does not exist. You could try this:
> 
> ```
> {{ asset('storage-domain_test/image.png') }}
> ```
> 
> or maybe better:
> 
> ```
> {{ asset('storage'.env('APP_PUBLIC_STORAGE').'/image.png') }}
> ```
> 
> Let me know if it works.
> 
> Cheers
> 
> Giacomo

I tried this but it does not work:

Also added `filesystem.php` text as per documentation:
````
public' => [
    'driver' => 'local',
    'root' => storage_path('app/public'),
    'url' => env('APP_URL') . '/storage' . env('APP_PUBLIC_STORAGE'),
    'visibility' => 'public',
]
```


But when I tried to access any env & config('app.asset_url') this thing also does not work it does not work as excepted

the app.app_name only works others does not returns empty data/null
