### ISSUE TITLE
SSL/HTTPS for the domains

### ISSUE THREAD

**Issue by nasirkhan** [gecche/laravel-multidomain#19]
Is it possible to use SSL for the individual domains? if so is there any doc for that?

**Comment by gecche** [comment]
Hi,

yes, each domain name works both with HTTP and HTTPS.
From the viewpoint of Laravel and my package you don't have to do anything, simply add a new domain, e.g. `site1.com` and it works with both schemas.
Obviously you have to handle the SSL in apache/nginx etc...

Cheers

Giacomo
