### ISSUE TITLE
Opinion

### ISSUE THREAD

**Issue by buruhsd** [gecche/laravel-multidomain#2]
I have an opinion, if it have a function  domain:list to show completly list of domain on system. and saving domain list to database

**Comment by gecche** [comment]
hi,

yes, it is a feature in development and it is planned for the next release. as soon as possible :)

thank you

giacomo

Inviato da iPhone

**Comment by buruhsd** [comment]
can i fork this repo, and develop this again?

**Comment by buruhsd** [comment]
because i need some tweak for my own project,

**Comment by gecche** [comment]
obviously! you are welcome!

let me know if you add some feature which can be useful to the main repo!

I will alert you if I add the domain list feature shortly so you can merge your code if needed.

please leave a star if you liked the project ;)

thank you

giacomo



Inviato da iPhone

**Comment by buruhsd** [comment]
okay, can i know your email so i can alert you some feature?

**Comment by gecche** [comment]
giacomo.terreni@gmail.com

Il giorno ven 15 mar 2019 alle ore 10:33 muhammad al jawad <
notifications@github.com> ha scritto:

**Comment by buruhsd** [comment]
okey thanks
