### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by nechin** [gecche/laravel-multidomain#20]
Hi.

What about a subdomains like **api.domain.com** or ***.domain.com**? It's not working for configuration file with the name _.env.domain.com_.

Thanks.

**Comment by gecche** [comment]
hi,

you should add a “domain” for each subdomain you want to use: the subdomain api.domain.com should use the .env.api.domain.com file.

to date, it is not handled the * wildcard for subdomains: each one must be added and if the specific .env.subdomain file is not found, the default .env is used

hope it helps

thanks

Giacomo

**Comment by nechin** [comment]
Yes, this is obvious. But you don’t want to add a row filter (or mask) for the domain name to somehow group the results? To have multiple subdomains use the same settings file?

Thanks.

**Comment by nechin** [comment]
This solution will give flexibility to your extension. So that I do not have to make changes on my own.

**Comment by gecche** [comment]
Hi,

I didn't think about this possibility before... So, do you mean to find a solution to "group" subdomains? It could be useful in some settings.

However I'm not sure your implemented solution works in all contexts, e.g. artisan commands or queues... have you tried it?

Maybe a simpler solution which gives a good degree of flexibility could be to check for default env file and default storage folder stripping down recursively subdomain parts, e.g. considering a subdomain `one.api.domain.com` and `two.api.domain.com`, the package would search for exact env files, and then it would search for` .env.api.domain.com`, then `.env.domain.com` and finally for `.env`.

This should be quite simple to implement. What do you think?

Cheers

**Comment by nechin** [comment]
> This should be quite simple to implement. What do you think?
Yes, that would be a great solution and would solve my problem.

**Comment by gecche** [comment]
ok! which version are you using? I will implement the feature on your branch before to release it as proper tags with all the docs and tests updated

**Comment by nechin** [comment]
Version 1.2.x

**Comment by gecche** [comment]
Ok, I've just pushed the modified version (tested) on branches v1.1 and v1.2.
Please check the functionalities... as I will take some more time to release the proper tags on all branches.

Cheers

giacomo

P.S.: If you haven't done yet, please give a star to the project ;)

**Comment by nechin** [comment]
Sorry, I can’t give a detailed answer. Now I can not check your solution. However, it looks the way I need it.
