### ISSUE TITLE
Domain parameter not defined with supervisor

### ISSUE THREAD

**Issue by nechin** [gecche/laravel-multidomain#21]
Hi.

I use a Docker with worker container and supervisor in it. In worker config file I defined the `command=/usr/local/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3 --domain=domain.com`.  The supervisor defined as ENTRYPOINT in Dockerfile (with worker config).
So in **detectDomain** method the **argv** parameter don't have the _domain_ key. Therefore, the scheduler always uses the **.env** config file.

Any ideas?

Thanks.

**Comment by gecche** [comment]
I have used Docker but I'm not very expert... anyway... Do you mean you use supervisor together with the Laravel schedule:run command?
In this case, you should add the domain option to the schedule:run command too and so run a scheduler for each domain.

But maybe I totally did not understand your problem.

Cheers

Giacomo

**Comment by nechin** [comment]
I can use domain option only in the worker file (see below). Not in schedule:run command (it used in dockerfile like **RUN crontab /etc/crontabs/laravel.cron**).
In any case, keep this option in mind. It is not compatible with your extension.

Thanks.

**Comment by MrCanan** [comment]
Hi,
But, is the --option in scheduler:run works outside/without docker for you?
Because it seems not working in my case ?
Or I missed something ^^
Because the artisan command with --domain option works in terminal, same with scheduler:run command, but not of in cron (crontab -e)
Best regards

**Comment by gecche** [comment]
Hi,

I'm not sure I understood your question.... however I use my package together with crons and WITHOUT docker in a lot of projects. 
The trick is that you have to launch one cron process for each domain, for example this is a crontab line:

`
* * * * * php PATH_TO_ARTISAN/artisan schedule:run --domain=DOMAIN_NAME >> /dev/null 2>&1
`

Cheers

Giacomo

**Comment by MrCanan** [comment]
Hi,
Thank you for your answer,
I do the same,
My artisan command works alone, but nothing in cron,
So I have perhaps an issue with new scheduler system of Laravel 11
