### ISSUE TITLE
Storing multiple `.env` files

### ISSUE THREAD

**Issue by mintymatt** [gecche/laravel-multidomain#22]
Hey,

⭐Fantastic package! Does a lot of heavy-lifting that I didn't expect to find, thank-you OP :)

I've begun extending it a little further for my own needs, do you have any suggestions for how to store the `.env.site.com` files?

Currently I will have around ~100 `.env.site.com` files sat in the root directory, I'm wondering how it could be possible to move into a subfolder like `env/...` or something...

What are your thoughts?

Best,
Matt

**Comment by gecche** [comment]
Hi! Thank you very much for your feedback :)

I think the possibility of storing env files elsewhere out of the root folder would be a nice addition to the package in a setting with many domains.

Maybe the most simple and effective way to implement is by adding a parameter to the Application class to specify the folder. I think it would not be so complex to get it.

I could add it in the next release but honestly I don’t have a timeline. However if you plan to do this, any pull update is welcome :)

Let me know

Cheers

Giacomo

Inviato da iPad

**Comment by gecche** [comment]
Hi, i just released new tags for all the branches with the new env folder option.
Also tests and doca have been updated.
I close the issue, thanks
