### ISSUE TITLE
run artisan config:cache without --domain

### ISSUE THREAD

**Issue by eraporsmk** [gecche/laravel-multidomain#24]
When run artisan config:cache without --domain, will create new file config-.php, not replacing to config.php file

**Comment by gecche** [comment]
Ok, I will check asap the issue

Thanks

Giacomo

**Comment by gecche** [comment]
Which version of the package do you use?

**Comment by eraporsmk** [comment]
laravel 5.8.*
here my composer https://github.com/eraporsmk/eraporsmk/blob/master/composer.json

**Comment by gecche** [comment]
Hi,

I've just done some additional test on the branch 1.4 corresponding to your Laravel version and I did not notice any problem. I have the standard config.php file cached in the bootstrap/cache folder.

In order to going deeper in the issue, could you just print out the result of these methods from within a CLI command?

1 - app()->getCachedConfigPath() and
2 - app()->environmentFile()

If you don't want to do a custom command you can also add an `echo $envFile` print in the `Gecche\Multidomain\Foundation\Application` class in my vendor folder at line 207 and re-run the config:cache command.

Let me know

Cheers

Giacomo

**Comment by eraporsmk** [comment]
![artisan](https://user-images.githubusercontent.com/53444184/79861662-f004ce00-83fe-11ea-8ca3-60e314c09977.jpg)
here the result of echo $envFile

**Comment by gecche** [comment]
It is a bit strange because the result should be `.env` (as in my tests) and not `.env.`. 
But do you have a  `.env.` file in your root folder? If so, you should delete or rename it and it should just work

Let me know

**Comment by eraporsmk** [comment]
I was deleted the .env.example file and was deleted config.php manually and re run artisan config: cache, but the result is still the same

**Comment by eraporsmk** [comment]
![artisan](https://user-images.githubusercontent.com/53444184/79864939-85569100-8404-11ea-812b-61bba0917a60.jpg)
here my root folder

**Comment by eraporsmk** [comment]
![artisan](https://user-images.githubusercontent.com/53444184/79932356-8ecd1100-8477-11ea-8b40-60b6602b2ed4.jpg)
the result

![config](https://user-images.githubusercontent.com/53444184/79932426-adcba300-8477-11ea-9b78-68a372857cb3.jpg)
the config

**Comment by gecche** [comment]
Hi,

I have seen the first screenshot: but it seems that you don't have the last 1.4 version of the package. I released version 1.4.5 on Sunday and your code seems to be part of an older release. : Did you do a `composer update` recently?

Anyway, if the problem persists, the echoing that I suggested you has to be placed before returning line within the `environmentFileDomain` method (Line 130 in 1.4.5 version)

Let me know

Giacomo

**Comment by eraporsmk** [comment]
![artisan](https://user-images.githubusercontent.com/53444184/79998179-92e34800-84e4-11ea-8e88-ef49309cd4db.jpg)
composer update

![artisan2](https://user-images.githubusercontent.com/53444184/79998202-9a0a5600-84e4-11ea-991e-8dabd5bf9c1b.jpg)
artisan config:cache

![config](https://user-images.githubusercontent.com/53444184/79998249-a7274500-84e4-11ea-914f-89ffd602ec39.jpg)
config

**Comment by gecche** [comment]
yep! 
It seems that the `file_exists` function is returning TRUE on the file `C:\eRaporSMK\dataweb\.env.` which instead you showed me it does NOT exist. 

Really I don't know if it is a general problem or in your setting and I'm not able to investigate further.

Anyway, I will release a bug fix release which will avoid that check when no domain is specified. In the meanwhile, you could simply rename manually the file `config-` in `config`

I will notify you when the new release it is ready.

Cheers

Giacomo

P.S.: If you liked the package please leave a star on the project If you haven't done yet! Thanks ;)

**Comment by gecche** [comment]
Hi,

I've just released the new versions of the package.
Now, it should completely avoid that check if no domain is provided.

Hope it works!

Let me know, for now I close the issue

Thanks

Giacomo

**Comment by eraporsmk** [comment]
very very nice...  its work
![artisan](https://user-images.githubusercontent.com/53444184/80148860-de2e5100-85df-11ea-9cdd-952e0de2598c.jpg)

note: i was upgraded my app into laravel 7x

**Comment by gecche** [comment]
👍 glad that it works!

However it should work both with 5.8 and with 7.x... i hope!
