### ISSUE TITLE
artisan config:cache --domain problem

### ISSUE THREAD

**Issue by enstat** [gecche/laravel-multidomain#27]
Hello,
I'm using laravel 5.5.49, I've followed your installation instruction but when I do the command ex: "php artisan config:cache --domain=site2.com" it doesn't create the "config-site2_com.php" file in bootstrap/cache directory, so the "multi-domain" feature doesn't work and it read only 1 .env file (I suppose the default .env). Is there any way to fix it?

**Comment by gecche** [comment]
Hi,

you should give me some more info, for example:

- your problem happens only when running the config:cache command or for any command?
- can I see your code and/or your folder structure?
- any other detail that could let me help you: obviously there could be a bug but in general the package is fully tested and for example I have in production a couple of projects with Laravel 5.5 and it works without problems.

Cheers

Giacomo

**Comment by enstat** [comment]
I was using an old version 1.1.0, I've updated to 1.1.12 and now it works good. Thanks you so much!
