### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by elephantux** [gecche/laravel-multidomain#3]
What about queue? Is it use .env.domain or default .env?
I need different MAIL_FROM_ADDRESS for domains.

**Comment by gecche** [comment]
Hi,

You can use the option —domain=YOURDOMAIN in your queue command and it should work properly loading the .env.YOURDOMAIN file.

Let me know if you have any problem

Giacomo

Inviato da iPad

**Comment by elephantux** [comment]
Thanks, i will try it now!

One more question. Is it possible create local domain which no need to commit? I mean separate domain names in local and production env.

**Comment by gecche** [comment]
hi,

sorry but I don’t understand your question, can you provide a concrete example? im not very good in english

giacomo

p.s.: if you like the package please leave me a star :)

Inviato da iPhone

**Comment by elephantux** [comment]
In local computer where I develop my app I use domain: myproject.dev
But in production server domain will be: mydomain.com
For now I need to create to domains (myproject.dev, mydomain.com) and commit it to git.

Is it possible to create and git ignore local domains?

**Comment by gecche** [comment]
yes it is possible: simply put the storage folder and the .env file of a domain in your .gitignore 

giacomo

Inviato da iPhone

**Comment by elephantux** [comment]
But the settings are also recorded in the configuration file. It's ok?

> yes it is possible: simply put the storage folder and the .env file of a domain in your .gitignore giacomo Inviato da iPhone

**Comment by gecche** [comment]
yes you are right, but from the package perspective they are stored in the config array only for displaying in the domain:list command.

no problem if you have an uninstalled domain entry in that array.

giacomo

Inviato da iPhone

**Comment by elephantux** [comment]
Thanks! Great package and solution. You save my time.

**Comment by elephantux** [comment]
> Hi, You can use the option —domain=YOURDOMAIN in your queue command and it should work properly loading the .env.YOURDOMAIN file. Let me know if you have any problem

It's not work for me. I have one supervisor config with this settings:
```
[program:default-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/domain1.com/artisan queue:work --sleep=3 --tries=3 --queue=default,domain1.com,domain2.com
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile= /var/www/domain1.com/worker.log
```

All queue emails sent with settings from default .env config.

**Comment by elephantux** [comment]
Sorry, I missing --domain options but result is the same...

**Comment by elephantux** [comment]
```
php artisan queue:work --sleep=3 --tries=3 --domain=domain2.com
```

this command run all queue with 'default' title only

**Comment by gecche** [comment]
Hi,

I need some more details of your code for trying to help.

I have a similar setting with supervisor in a production app with Laravel
5.1 with over 15 domains and it works: obviously I have the same number of
queue:work processes running simultaneously each one with the specified
--domain option.

However I have just tried on my machine with Laravel 5.8 using two domains
site1 and site2.
In both .env files I've put a line TEST=site1|site2.
The queue driver I tested is "database" and I ran the queue migration in
the two databases.

I've created a ProcessTest in App/Jobs such that

public function handle()
{
    var_dump(env("TEST",'test'));
}

Further I created a route "testqueue" which simply dispatch the ProcessTest job.

First I ran

php artisan queue:work --domain=site1

and correctly it handled the job from http://site1/testqueue displaying
"site1" and it did not handled the same job from http://site2/testqueue

Then I ran

php artisan queue:work --domain=site2

and correctly it handled the previously launched job from
http://site2/testqueue displaying "site2".

Maybe there is a problem with another queue driver? Can you try a similar
simple setting like mine?

Cheers

Giacomo


Il giorno dom 5 mag 2019 alle ore 20:24 Yury Boichuk <
notifications@github.com> ha scritto:

**Comment by elephantux** [comment]
I repeated ProcessTest and it's work.
Sorry man I has some problems because change queue names due previous experiments. 
Now all work fine!

Big thanks for your time and assistance!

**Comment by gecche** [comment]
I'm happy it is working! :)

Cheers

Giacomo

Il giorno dom 5 mag 2019 alle ore 22:13 Yury Boichuk <
notifications@github.com> ha scritto:

**Comment by elephantux** [comment]
@gecche hi again.

Problems remained. I can't understand with queue workers. How this work?

I have .env.site1.com and .env.site2.com for two domains. It's ok. 
Problem: I need to send mail notifications from @site1.com or @site2.com depending on what domain the user did the action.

I run 2 supervisor workers for each domain:
```php artisan queue:work --sleep=3 --tries=3 --domain=site1.com```
```php artisan queue:work --sleep=3 --tries=3 --domain=site2.com```

But now emails from the queue are sent depending on which worker is the first to work.
How to solve this? As I understand queue Jobs in MySQL do not store domain info...

**Comment by gecche** [comment]
Hi,

one first question: site1.com and site2.com share the same db?

giacomo

Inviato da iPhone

**Comment by elephantux** [comment]
> one first question: site1.com and site2.com share the same db?

Yep

**Comment by gecche** [comment]
Ok, indeed I never tried this case because in my settings I've always a
distinct db for each domain, thus guaranteeing that each worker respond
only to his jobs.

I will think how to solve this problem and if it is possible... I don't
know if it is a simple fix.
Could you send me a working example of your settings? But you could not
incorporate in your command a reference to the domain in which has been
launched?

Giacomo

Il giorno ven 17 mag 2019 alle ore 10:02 Yury Boichuk <
notifications@github.com> ha scritto:

**Comment by elephantux** [comment]
> Could you send me a working example of your settings?

Which settings? Supervisor config?

> But you could not incorporate in your command a reference to the domain in which has been
launched?

What do you mean?

**Comment by gecche** [comment]
Il giorno ven 17 mag 2019 alle ore 15:14 Yury Boichuk <
notifications@github.com> ha scritto:

> Could you send me a working example of your settings?
>
> Which settings? Supervisor config?
>
But you could not incorporate in your command a reference to the domain in
> which has been
> launched?
>
> What do you mean?
>
> —
>

I mean if you can send me an example of your working code for testing and
possibly find out a solution   :)

**Comment by elephantux** [comment]
I got one Laravel Project with one DB. I also have two domain names which use the same Laravel project. All what I need is different mail_from when send notifications and different views for some parts of projects. That's all.

I think what solution may be to use in one domain config database queue and in another domain redis.

**Comment by gecche** [comment]
Ok, thanks, I will try to see what can be done in the case of two domains
with the same db. I hope to have some time in the weekend

Giacomo

Il giorno ven 17 mag 2019 alle ore 15:33 Yury Boichuk <
notifications@github.com> ha scritto:

**Comment by gecche** [comment]
Hi,

just a possible solution.

When you dispatch a job you could specify a queue depending on the domain
.env.

For example if you have in .env.site1.com

MAIL_QUEUE=queue1

and in .env.site2.com

MAIL_QUEUE=queue2

you could dispatch the process, let say ProcessTest with
ProcessTest::dispatch()->onQueue(env('MAIL_QUEUE','default'))

At the same time the queue artisan commands should be

php artisan queue --domain=site1.com --queue=queue1
php artisan queue --domain=site2.com --queue=queue2

I did not try, but it should work if I understood well the queue command.

Let me know

Cheers

Giacomo


Il giorno ven 17 mag 2019 alle ore 15:37 Giacomo Terreni <
giacomo.terreni@gmail.com> ha scritto:

**Comment by elephantux** [comment]
Yes, this solution work!
Perfect! Thank you again and again!

**Comment by elephantux** [comment]
If queue name will has the same name as domain (env) maybe it can be implemented in the package code?

**Comment by gecche** [comment]
yes... I was thinking about it... I think that for a more general solution a “domain” info has to be added to the job...

I hope to have time asap to improve the package

thank you

giacomo

Inviato da iPhone

**Comment by gecche** [comment]
Hi,

I’ve just updated the package improving the readme section with a specific queue paragraph.

At last, I think that an automatic and general for your setting is not easy (at least) and possibly not right at all because it has various and not straightforward implications.

I think that the best solution is to specify a default queue for each domain directly in the configuration file if needed.

Thank you

Giacomo

Inviato da iPad
