### ISSUE TITLE
Issue with the www subdomain

### ISSUE THREAD

**Issue by dickalexei** [gecche/laravel-multidomain#30]
Hi! 
First of all, thank you for this package :)!

# Description
I have an issue with my subdomain when use "www" subdomain.
Maybe it's a configuration issue but not sure, need help :).
# Prerequisites
- have mydomain.com configured
- add mydomain.com with `php artisan domain:add mydomain.com`
# Scenario
- browse 'https://mydomain.com` -> OK
- browse 'https://www.mydomain.com` -> NOK
# Observed result
Seems that DomainDetector is looking for a .env file using SERVER_NAME. 
Then here `.env.www.mydomain.com` is waited but only `.env.mydomain.com` is existing.
# Expected result
DomainDetector::detectWebDomain() should return domain name without www subdomain

I'm not aware of best practice of using or not the "www" subdomain. But would prefer to not rewriting the url in htaccess...

Regards.

**Comment by dickalexei** [comment]
This worked for me:

```
protected function detectWebDomain()
{
    //return filter_input(INPUT_SERVER,'SERVER_NAME');
    //return Arr::get($_SERVER,'SERVER_NAME');

    return preg_replace('/^www\./','',Arr::get($_SERVER,'SERVER_NAME'));
}
```

**Comment by gecche** [comment]
Hi,

first oof all thank you for your feedback!

I'm sure your solution works perfectly In your settings but I had a specific setting in the past in which www.site1.com and site1.com needed different behavior, so I'm not sure that it is the most general solution and in general I prefer to avoid string manipulations in that specific function.

By the way, I could suggest a simple workaround for now, and two solutions which can be implemented soon.

1 - (WORKAROUND) For now you can also add the www.mydomain.com configuration: if you need exactly the same .env file and the same storage folder, you can rewrite them manually as symbolic links

2 - (SOLUTION PARTIALLY IMPLEMENTED) As discussed in #20 , I'm planning to use "defaults" configurations based on the domain structure. So if you add a configuration for , e.g.`domain.com`, al the subdomains like `site1.domain.com` and `site2.domain.com` inherit the same configuration unless you add a specific one. This solution should work for you and it adds flexibility to the package. It is already implemented and tested in branches 1.1 and 1.2 (but it is outside the tags, so if you are using right now, the 1.1.* version and you want to try it, you have to put "v1.1.x-dev" in the composer.json. I plan to extend this solution to all branches very soon, I'm only a bit afraid that it could break some existing settings, but probably not.

3 - (SOLUTION TO BE IMPLEMENTED) I thought some time ago about the possibility of adding a further parameter in the main application constructor, accepting a Closure for a user-defined "web domain detection". It should be easy to implement but I didn't know how much value it would add. With that, you can easily use your logic for your specific setting.

I hope this helps and let me know what you think

Cheers

Giacomo

**Comment by dickalexei** [comment]
Hi,

Thank you for quick reply!

Agreed regarding strings manipulations. My solution was just a temporary workaround. 

Solution 2 seems good to me... I'm using 1.4 version then I can wait the official release no problem. 

Please feel free to close this issue :).

Regards.

**Comment by gecche** [comment]
Hi,

it took me a while but finally I've just released the "Solution 2" in all the versions of the package.

I close the issue

Cheers,

Giacomo
