### ISSUE TITLE
What is the method of establishing ownership of the site !!

### ISSUE THREAD

**Issue by odaiderawi** [gecche/laravel-multidomain#31]
Hey 
thank you in advance
I have a question :  how to establishing ownership of the site ? 
I mean anybody can have example1.com domain in his code but how to config the domain with my application

**Comment by gecche** [comment]
hi,

what do you mean exactly with “ownership” in this context? could you explain with a concrete example? maybe it’s due to my english but I don’t understand your question.

cheers

giacomo

Inviato da iPhone

**Comment by odaiderawi** [comment]
let say i have the example1.com domain. and i have the example2.com domain and i need to make dashboard to control these two domains 
how your package validate that you really own these domains ?

**Comment by gecche** [comment]
hi,

the package absolutely does not validate if you are the real owner of the domains, but this check should be done at the DNS level not at the application level.
if you are not the owner, your server does not receive the requests for the domains.

let me know if you meant another thing

cheers

giacomo

Inviato da iPhone

**Comment by gecche** [comment]
Hi,

as you did not reply, I close the issue

cheers

Giacomo
