### ISSUE TITLE
Support for Laravel 8

### ISSUE THREAD

**Issue by andrecolza** [gecche/laravel-multidomain#34]
Hi Giacomo,
Could you please add Laravel 8 support to your package?

Thank you!
Andrea

**Comment by gecche** [comment]
yes, it is obvioisly planned... I hope this week to be able to update... however I’m a bit busy these days and maybe it could be delayed to next week

cheers

giacomo

Inviato da iPhone

**Comment by gecche** [comment]
Just released! :)

I close the issue but any feedback is appreciated 

Cheers

Giacomo
