### ISSUE TITLE
Lumen support?

### ISSUE THREAD

**Issue by sn0rk64** [gecche/laravel-multidomain#35]
Does this library support lumen?

**Comment by gecche** [comment]
Hi,

actually, I have never used Lumen, so the official answer is no.
However, It could be a nice future feature adding support to Lumen and
maybe it could be quite straightforward to implement.

Any help would be appreciated

Cheers

Giacomo



Il giorno ven 16 ott 2020 alle ore 15:01 sn0rk64 <notifications@github.com>
ha scritto:
