### ISSUE TITLE
Bug: Queue is not compatible with newer versions of Illuminate\Queue

### ISSUE THREAD

**Issue by Deprecator** [gecche/laravel-multidomain#37]
Hello there. We integrated your package with one of our projects and came across the follwing issue: running queue:listen command with --domain option doesn't work as expected. The QueueListen command signature is different from the newer versions so the option won't get passed to queue:work command. I have worked this issue out and here's the fix.

**Comment by gecche** [comment]
Hi,

thank you very much for your feedback and your fixes!

I hope to have the right time in the weekend to check out your code and to release the new version... at last I will do next week :)

Cheers

Giacomo

**Comment by gecche** [comment]
I've just released version 4.1 including your changes. Thank you very much :)

Cheers 

Giacomo

P.S.: If you liked the package please leave a star if you haven't done yet :)
