### ISSUE TITLE
Scheduled commands not dedecting the environment

### ISSUE THREAD

**Issue by satheesh365** [gecche/laravel-multidomain#43]
@gecche, I have few commands scheduled in main scheduler Console\Kernel.php. When I run the scheduler with --domain option, the subsequent commands are not aware of the domain. I have to pass the --domain option to each command explicitly.

Ex:
php artisan schedule:run --domain=demo.mysite.com

I have another command scheduled as 

$schedule->command("article:update-status")->hourly();
But this is not working. So I have to pass domain like below for each command.

$domain = app('domain');
$schedule->command("article:update-status --domain=$domain")->hourly();

Is this expected behaviour?

**Comment by gecche** [comment]
Hi,

Yes you have to do so. It was already discussed in #8 where you can find an example. Maybe I should better specify it in the main docs.

Cheers,

Giacomo
