### ISSUE TITLE
View and controller

### ISSUE THREAD

**Issue by StrangerGithuber** [gecche/laravel-multidomain#44]
Hello
I have a question or maybe two.
I don't understand how to give blade files (where I should put them) to the different domains and how to put the view in controller? With folder path?

**Comment by gecche** [comment]
Hi,

my package is intended to manage multiple domains at a very high level, implementing only the (not straightforward) part of having a specific .env file for each domain together with a specific storage folder, and giving a tool for using artisan commands and queues for each domain.

There is no assumption my package does regarding controllers and views as for many other application parts. Once you have a runtime tool for  distinguishing the domain under where you are, you can use it to switch between database, routes, controllers, views and whatever you want, testing either environment variables or the domain name directly e.g. in a route file you can do:

```
...
switch (app()->domain()) {
   case 'site1.test':
       Route::get('test1','Site1Controller@test1');
   break;
   default:
   break;
}
...
```

or in a controller you can do:

```
...
switch (env('THEME')) {
   case 'group1.test':
       return view('group1');
   break;
   case 'group2.test':
       return view('group2');
   break;
   default:
      return view('default');
   break;
}
...
```

It is completely up to you to choose how to apply different logic for each domain or for a group of domains.

If your use case is to have a single code base together with multiple front-end themes, IMHO you should try to use my package in combination with [Laravel Theme Package](https://github.com/igaster/laravel-theme) as pointed out also in #12, as I do in many of my projects.

Hope this helped

Cheers

Giacomo

P.S.: If you like the package, please leave a star, If you haven't done yet :)

**Comment by StrangerGithuber** [comment]
Yep. I did.
I like this package. It helps a lot to make easier the life. I have just 3 websites and it helps me to reduce the file usages because many webhostings have inode limitation and it helps me to not hit the limit. Thank you for the answer and package. 

So if I understood correctly. I will use normally the Controller folder and the resources/view folders.
Last question is, where I put the javascripts, css, images files? Normally in the public folder?
Thank you in advance for the answer. 👍

**Comment by gecche** [comment]
Hi, thanks for your feedback!

Yes, you should use the standard public folder. Again, if you plan to distinguish the assets folders among the various domain, you should consider to use, in combination with mine, the Theme package I suggested before.

Cheers

Giacomo

**Comment by StrangerGithuber** [comment]
Alright. Thank you for the answer and I will look into your other package. 👍

**Comment by gecche** [comment]
Glad to have helped you :) 
however the other Theme package is not mine :) I only suggested you a good package (IMHO) which I use since many years.
