### ISSUE TITLE
Question: Jetstream

### ISSUE THREAD

**Issue by StrangerGithuber** [gecche/laravel-multidomain#46]
Hello
I am confused very much nowadays. So much to do within one laravel and not sure if jetstream will work without problem on different domains.
Did someone try laravel jetstream with laravel multidomain? 
Does it working fine without problems or redirection is confusing for jetstream? Or something else can be the problem?

**Comment by gecche** [comment]
Hi,

I'm sorry for the delay but I was off some days and then I had a lot of work to do :)

Honestly, I've never used Jetstream but I don't see any problem and I think that Jetstream should work just fine combined with my package... 

So I simply close the issue: If you or anyone else find an issue, please reopen!

Cheers

Giacomo
