### ISSUE TITLE
Can't link multiple stoarge for doamins.

### ISSUE THREAD

**Issue by ajeshvc** [gecche/laravel-multidomain#50]
Added this package to my project and its working fine. I need to link separate storage for each domains and it fails.
Uses this steps in Readme : 
```
ln -s storage/site1_com/app/public public/storage-site1_com 
ln -s storage/site2_com/app/public public/storage-site2_com 
```
and shows the following error.
```
"ln : The term 'ln' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again. At line:1 char:1"
```
The path i used is correct too.. help pls..

**Comment by gecche** [comment]
hi,

it’s seems that your shell does not recognize the command “ln”...

if you are not using linux, you should use the right command for creating a symbolic link

hope this helps

giacomo

**Comment by ajeshvc** [comment]
Thanks
