### ISSUE TITLE
Issue with storage link for multiple domains, saving to 

### ISSUE THREAD

**Issue by newlaravelcoder** [gecche/laravel-multidomain#59]
Hi,
I uploaded an image file which saves into /storage/superlaravel_test/app/public/3/ - It's perfect.

But, when I preview the image, it shows me as => http://superlaravel.test/storage/superlaravel_test/3/file.png
            "/app/public/" is missing in the generated link. I wonder why.

My .env.superlaravel_test file has 
          **APP_PUBLIC_STORAGE=superlaravel_test**        _===> is this correct or should I add "/app/public/"_

My filesystems.php has
        'url' => env('APP_URL').'/storage'.'/'.env('APP_PUBLIC_STORAGE'),  _====> should I add here?_

What am I doing wrong? 

Thank you for your time,

Regds,
newbie

**Comment by newlaravelcoder** [comment]
Solved it.

**Comment by edwinsmasher** [comment]
How did you solve it? am also having the same issue

**Comment by vserdobintsev** [comment]
@newlaravelcoder, in version 6 of Laravel, you can only use the second version of your product. It's not fixed there.

**Comment by gvrevillac** [comment]
> Solved it.

how did you solve this
