### ISSUE TITLE
fire tasks for new domain

### ISSUE THREAD

**Issue by maganius** [gecche/laravel-multidomain#60]
I need launch some tasks when a new domain is added, I need start this after make `php artisan domain:add`.

how I can solve this?

**Comment by gecche** [comment]
Hi,

I'm sorry for the delay but I'm very constrained in these weeks... 

I think that there is not a general way to solve this: I think that the best solution is that you should fork the repository and overwrite the command if you need this... usually after the domain:add command you also have to customize the .env before to do anything else. So I don't know how to solve this in a general and simple way: if you have any idea please consider to share it here :)

Cheers

Giacomo
