### ISSUE TITLE
Problem generating pdf in multi tenant applications

### ISSUE THREAD

**Issue by cavajr** [gecche/laravel-multidomain#63]
Hi. I use the barryvdh/laravel-dompdf package with livewire often and I have no problems. When using it with livewire and any package, for example gecche/laravel-multidomain, that works with tenancy is not generating the pdf. Any incompatibilities when working with tenancy regarding file system or cache?

**Comment by gecche** [comment]
hi,

I’m using extensively the snappy library and I never had a problem regarding multiole domains.
I never used dompdf in multi domain projects but I don’t think there is any incompatibility.

for regarding file system/cache I don’t know about any issues, however please consider to follow the docs for caching the config

I close the issue: if you have a more detailed and specific problem, please reopen it

Cheers
