### ISSUE TITLE
Updating env of a specific domain seems to update all .env files

### ISSUE THREAD

**Issue by ccargill-ewx** [gecche/laravel-multidomain#67]
Hi,

this code has been really helpful in bridging the gap in our product however, looking at the documentation, either I am missing something or the parameter to specify which env file to update seems to get ignored and proceeds to update all files? 

`php artisan domain:update_env --domain=testdomain.com --domain_values='{"TOM_DRIVER":"TOMMY"}'` is how i assumed this would be structured, so am I missing something?

Many thanks!

**Comment by NettSite** [comment]
Does the same for me.

Best regards,

*William Nettmann*
*Office: 010 013 0525*
*Mobile: 082 309 4007*


[image: Facebook] <https://www.facebook.com/NettSite> [image: Twitter]
<https://twitter.com/NettSiteCoZa> [image: Google+]
<https://plus.google.com/+NettsiteCoZa> [image: LinkedIn]
<http://www.linkedin.com/company/1082367?trk=tyah&trkInfo=tas%3Anettsite%2Cidx%3A1-1-1>

**Comment by gecche** [comment]
Hi all,

I will check asap the issue.
Actually, I never use that command :) 
I thought about dropping it in future release but it seems that some of you are using it, so I will keep it in the package :)

Could you tell me which version are you using?

Cheers

Giacomo

**Comment by ccargill-ewx** [comment]
Hi thanks for getting back. Yes please keep this in the release its really helpful for one of our products! We are using the latest version with Laravel 8.

Many thanks

**Comment by gecche** [comment]
Hi all,

I haven't had time to try yet, but re-reading your messages, I think that there is only a "bug" in the documentation! :)
If you want to update only one specific env file, you should specify the domain name as an argument and not as an option (as wrongly written in the docs):

`php artisan domain:update_env testdomain.com --domain_values='{"TOM_DRIVER":"TOMMY"}'`

Let me know if it works properly (I think yes)... I will update the docs accordingly

Cheers

Giacomo
