### ISSUE TITLE
Mutli doamin is not working Laravel Passport

### ISSUE THREAD

**Issue by sulaman0** [gecche/laravel-multidomain#69]
Multi domain is not working with laravel passport, It working only Main Domain only.
On other domain its throwing error 

`{
    "message": "Server Error"
}`

**Comment by gecche** [comment]
Hi,

I'm sorry but I can't even try to solve the issue without further details.

The package is intended to work with Laravel and many other added packages, but there can be some incompatibilities and obviously I cannot check every Laravel package. :)

Anyway, I'm currently using it with a lot of other Laravel packages without problems and as pointed out in #51, my package seems to work properly with Passport. 

So I close the issue until you have more details to share pointing out which is the specific problem in my package

Cheers

Giacomo
