### ISSUE TITLE
Not working with 2nd domain

### ISSUE THREAD

**Issue by tuvataliya2141** [gecche/laravel-multidomain#76]
Hello @gecche ,
How are you?

I followed all the steps from first to last but when I run the last command " php artisan queue:work --domain=site1.com --queue=default1" so it's stuck nothing to any process and when I try to run the domain so it's showing 404 error.

I am doing this all process into cPanel.

Can you please guide me with that?

Thank you and Regards,
Tarun Vataliya

**Comment by gecche** [comment]
Hi,

if you are getting a 404 error, I think that probably you misconfigured either the cpanel configuration or the Laravel route section...

However for trying to help you I need more details and see some code and/or configuration

Cheers

Giacomo

**Comment by tuvataliya2141** [comment]
Hello Giacomo,
Thank you for your reply!

I follow all the steps as per maintain in this README file. and there is nothing any type of instructions about the route file so can you please let me guide me with the route file? I mean what are the changes in the route file?

And I want to know I have 2 domains and if both the domain are in the same cPanel. For example., I have domain 1 and domain 2 and my Laravel project is configured in domain 1 I follow all the given steps for both domains with an every time successful response but when I try to fire the URL so it's not working.

Thank you again and Regards,
Tarun Vataliya

**Comment by gecche** [comment]
Hi, 

no, there aren't specific instructions for routes but as you get a 404 Error, maybe that domain is misconfigured in cpanel or in your server.

However in your first question you was talking about queues in artisan: which URL do you mean?

I'm sorry but until now I can't understand which is the problem related to my package :)

Cheers

Giacomo

**Comment by tuvataliya2141** [comment]
Hello,

There is nothing any problem with your code but I just want to ask you, when I run the "php artisan queue:work --domain=site1.com --queue=default1" command in last so nothing any progress. Should I get any result after fire this command?

Thank you!

**Comment by gecche** [comment]
Hi,

I think no: that command awaits for a job launched from the domain site1.com.
If you don't launch any job, It should keep waiting forever.

Cheers!

giacomo

P.S.: I close the issue, please reopen if you have any other problem
