### ISSUE TITLE
How this package works?

### ISSUE THREAD

**Issue by asifu5057** [gecche/laravel-multidomain#80]
Hi,

I just want to know how this package works?

I have a primary domain `site1.com`, all laravel files are there having .env file, now I want to add another alternative domain by running the command `php artisan domain:add site2.com` but on this domain no file exist so how this domain will work? or I should move the files to site2.com? please guide me.

Thank you.

**Comment by gecche** [comment]
Hi,

I'm sorry but I don't understand the question :)

Cheers

Giacomo

**Comment by gecche** [comment]
I close the issue as you didn't reply... if you still need some help please reopen it, 
cheers, Giacomo
