### ISSUE TITLE
Queue in Forge?

### ISSUE THREAD

**Issue by christoph-werker** [gecche/laravel-multidomain#81]
Hello Guys,

right now I'm struggling with the settings for the Queues with Forge.

I have in Forge the following Setting for my queues. Unfortunately i don't have a option for the `--domain` Parameter
<img width="1009" alt="Screenshot 2022-06-09 at 22 35 22" src="https://user-images.githubusercontent.com/9929788/172939764-6c8dc17c-6d91-43de-80dd-10f27086143d.png">

Has probably someone figured out how to achieve a success with an additional parameter for the worker in forge?

**Comment by gecche** [comment]
Hi, nope... as far as I know, it can't be done: you should ask directly to the maintainer of Forge (Taylor I suppose...)
I'm also using forge and I simply configure manually the supervisor processes when I need

Giacomo

**Comment by christoph-werker** [comment]
Hi Giacomo,

thanks for the fast Reply.


I'm, testing to add the Domain in the Environment field, and it could work. But it's untested and i'm waiting for tailor to answer me.
<img width="341" alt="image" src="https://user-images.githubusercontent.com/9929788/173031089-8b5a7a20-a450-41ee-aa2a-2d068f1c6886.png">

What is your best practice approach to do this? Because i need a solution that my employee could handle in case that i'm not available and there is an critical error?

**Comment by christoph-werker** [comment]
i got an answer from Forge. The Solution in my previous comment could work, but creating a new daemon should be better. 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/9929788/173068851-e347091a-009f-4ef6-91ae-0f3ed17a4263.png">
