### ISSUE TITLE
using with Laravel Valet in local developement

### ISSUE THREAD

**Issue by aurawindsurfing** [gecche/laravel-multidomain#82]
Hi @gecche and thanks for brilliant package!

I wonder how would one use this package with Laravel Valet.  Valet handles all domain names without issue but with different tld such as `store.test`, `samplestore.test` etc.

When I use the package I need to use actual domains the app will work with in production such as `store.com`, `samplestore.com`

What will be your solution to that, please? Should the domain name be matched but without the .tld or with override for local developement?

Thanks!

**Comment by gecche** [comment]
Hi, thanks :)

Maybe I don't understand properly the question: you have to use store.com and samplestore.com in your local environment?

Or what?

Cheers

Giacomo

**Comment by aurawindsurfing** [comment]
Yes, but obviously I need to configure it for `store.test` and `samplestore.test` to work properly so all the configs will be named incorrectly for production then.

My idea was to have domains without the TLD's so the config files can work both in production and developement. 

Maybe I'm missing something?

**Comment by aurawindsurfing** [comment]
Thanks for the time and advice!
