### ISSUE TITLE
Job won't open the correct .env-file in Job?

### ISSUE THREAD

**Issue by christoph-werker** [gecche/laravel-multidomain#84]
Dear Community,

i'am dispatching a Job like this and in my job i want to Send an API-Request. 

```php
Job::dispatch($user)->delay(now()->addMinutes(60*3));
```
For the Request i need the Keys from the correct ENV file. But unfortunately the Job open the `.env` and not the `.env.domain`
```php
$this->api = new Api(env('API_KEY'), env('API_DOMAIN'));
$this->api->action($this->var);
```

My Scheduler works with `php artisan schedule:run --domain=domain`

I hope that you understand my Question and know a solution.

**Comment by gecche** [comment]
Hi,

but from which domain you dispatch the job? I ask you because to my knowledge there is no way to run a command/job under a certain domain/environment if you launch it from within the Laravel script ran under another domain/environment.



Cheers

Giacomo

**Comment by gecche** [comment]
yes... to my knowledge there is no way to "change the environment" from within the application itself. There is the need of some "machinery" outside the application which dispatch the jobs among the domains.

I think that in some way this is similar to another issue #14 which also could be solved only using a proper shell script.

I hope this helps... I close the issue for now... be free to reopen if you need

Cheers

Giacomo
