### ISSUE TITLE
Can system use centralized user authentication?

### ISSUE THREAD

**Issue by HP161** [gecche/laravel-multidomain#85]
I want a centralized administration system for users, domains, .. for all websites.
Thanks for the feedback!

**Comment by gecche** [comment]
Hi,

the package allows to use the same codebase for N domains/websites.
But if you want a system which collects info form all such domains, I think you need to implement to distinct applications (one for the centralized stuff and one for the N domains/websites) or to use another approach than this package

Cheers

Giacomo
