### ISSUE TITLE
Supervisor work queue

### ISSUE THREAD

**Issue by raulamoretti** [gecche/laravel-multidomain#86]
Hey guys,

Yours package is amazing! We have 25 domains run in a server, a small server.
We have a elastic enviroment, but we have problems with queues, now we work with 3 queues by domain. Now we have a server with 25 * 3 queues running.

Someone has same problem? How unify queues and run job by domain?

Thanks!
<img width="1606" alt="Captura de Tela 2022-10-21 às 12 14 28" src="https://user-images.githubusercontent.com/2983421/197230884-17a392af-179a-4ebc-97b2-d359f756d302.png">

**Comment by gecche** [comment]
Hi, thanks for your feedback :)

I think that it is the normal behaviour of the package: you have N domains and so you have (N* 3) queue workers... 
I also have a production Laravel application with a lot of domains and queue workers... 
As pointed out in other issues, to my knowledge there is no way to "redirect" a job to a queue of another domain from within the Laravel App.

I think that if you have a server resource problem, the only thing you could do is to restructure your app, creating a second laravel application which only executes the queue jobs of the N domains of the main application communicating through an API. This is the only idea I thought.

Cheers

Giacomo
