### ISSUE TITLE
problem with directadmin

### ISSUE THREAD

**Issue by vakora** [gecche/laravel-multidomain#89]
hi guys, i used this package with my laravel project , in local setting when i add custome domain to windows host file everything is ok
but when i upload my project on serve i got error like this :

Laravel version : 9.42.2

![image](https://user-images.githubusercontent.com/4935395/215513843-26ea4ba1-347a-4d06-89cb-19b82928160f.png)
my dns setting in directadmin
![image](https://user-images.githubusercontent.com/4935395/215514179-43594845-81fa-4ec4-bae7-57036ab2380c.png)

my question is Where is my mistake?

**Comment by gecche** [comment]
Hi,

I think that if the DNS is the point, there is a configuration problem of your production machine but is totally outside the scope of my package.
If, otherwise, DNS is not the problem, I need some more details of the Internal Server Error for being of some help.

Cheers

Giacomo

**Comment by vakora** [comment]
solve this problem with enable wildcard on domain
